CREATE TABLE [dbo].[ArcadeMachine]
(
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[Name] NVARCHAR(64) NOT NULL,
	[GameName] VARCHAR(64) NOT NULL,

	CONSTRAINT [PK_ArcadeMachine] PRIMARY KEY ([Id])
)
